### ISSUE TITLE
iframe-resizer 探究

### ISSUE THREAD

**Issue by dailynodejs** [xinpianchang/fe-weekly#92]
源码地址：https://github.com/davidjbradshaw/iframe-resizer

(1)、介绍

此库允许自动调整相同和跨域iFrame的高度和宽度大小，以适应其包含的内容。它提供了一系列功能来解决使用iFrame时最常见的问题，包括：

根据内容大小调整iFrame的高度和宽度大小。

使用多个和嵌套的iFrame。

跨域iFrame的域身份验证。

提供一系列页面大小计算方法，以支持复杂的CSS布局。

使用MutationObserver检测可能导致页面调整大小的DOM更改。

（2）、典型设置
正常配置是在浏览器窗口大小更改或iFrame内容更改时调整iFrame的大小。要进行设置，您需要将iFrame的一个维度配置为百分比，并告诉库仅更新另一个维度。通常，您会将宽度设置为100%，并具有适合内容的高度比例。

        <style>
          iframe {
            width: 1px;
            min-width:
          }
        </style>
        <iframe id="myIframe" src="http://anotherdomain.com/iframe.html"></iframe>
        <script>
          iFrameResize({ log: true }, '#myIframe')
        </script> 

（3）、API 文档
            Parent Page API
                Options
                Events
                Methods
            IFramed Page API
                Options
                Events
                Methods
            Use with Libraries and Frameworks
                React
                Vue
                Angular
                Ember
                jQuery
                Google Apps Script
（4）、语法属性

         

         allow用于为<iframe>指定其特征策略.

         allowfullscreen设置为true时，可以通过调用 <iframe> 的 requestFullscreen() 方法激活全屏模式。

         name用于定位嵌入的浏览上下文的名称。该名称可以用作 <a> 标签与 <form> 标签的 target 属性值，也可以用作 
        <input> 标签和 <button> 标签的 formtarget 属性值，还可以用作 window.open() 方法的 windowName 参数值。

         src被嵌套的页面的 URL 地址。使用 about:blank 值可以嵌入一个遵从同源策略的空白页。在 Firefox （version 65及更高版 
         本）、基于 Chromium 的浏览器、Safari/iOS 中使用代码移除 iframe 的 src 属性（例如通过 Element.removeAttribute() ） 
         会导致 about:blank 被载入 frame。

（5）、源码分析

                 <html>
                      <head>
                        <meta charset="utf-8" />
                        <title>iFrame message passing test</title>
                        <meta name="description" content="iFrame message passing test" />
                        <meta name="viewport" content="width=device-width" />
                        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                      </head>
                
                      <body>
                        <h2>Automagically resizing iFrame</h2>
                        <p>
                          Resize window or click one of the links in the iFrame to watch it resize.
                          Or try with <a name="anchorParentTest" href="two.html">two iFrames</a>.
                        </p>
                        <div style="margin:20px;">
                          <iframe src="frame.content.html" width="100%" scrolling="no"></iframe>
                        </div>
                        <p id="callback"></p>
                        <div style="margin: 8px 0;font-size:13px;">
                          For details on how this works, see
                          <a href="http://davidjbradshaw.github.io/iframe-resizer/"
                            >http://davidjbradshaw.github.io/iframe-resizer/</a
                          >.
                        </div>
                    
                        
                        
                    
                        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
                        <script type="text/javascript" src="../js/iframeResizer.min.js"></script>
                        <script type="text/javascript">
                          /*
                           * If you do not understand what the code below does, then please just use the
                           * following call in your own code.
                           *
                           *   iFrameResize({log:true});
                           *
                           * Once you have it working, set the log option to false.
                           */
                    
                          var callbackDisplay = 'p#callback'
                    
                          iFrameResize({
                            log: true, // Enable console logging
                            inPageLinks: true,
                            onResized: function (messageData) {
                              // Callback fn when resize is received
                              $(callbackDisplay).html(
                                '<b>Frame ID:</b> ' +
                                  messageData.iframe.id +
                                  ' <b>Height:</b> ' +
                                  messageData.height +
                                  ' <b>Width:</b> ' +
                                  messageData.width +
                                  ' <b>Event type:</b> ' +
                                  messageData.type
                              )
                            },
                            onMouseEnter: function (messageData) {
                              // Callback fn when mouse enters iframe
                              $(callbackDisplay).html(
                                '<b>Frame ID:</b> ' +
                                  messageData.iframe.id +
                                  ' <b>ScreenX:</b> ' +
                                  messageData.screenX +
                                  ' <b>ScreenY:</b> ' +
                                  messageData.screenY +
                                  ' <b>Event type:</b> ' +
                                  messageData.type
                                )
                            },
                            onMouseLeave: function (messageData) {
                              // Callback fn when mouse enters iframe
                              $(callbackDisplay).html(
                                '<b>Frame ID:</b> ' +
                                  messageData.iframe.id +
                                  ' <b>ScreenX:</b> ' +
                                  messageData.screenX +
                                  ' <b>ScreenY:</b> ' +
                                  messageData.screenY +
                                  ' <b>Event type:</b> ' +
                                  messageData.type
                              )
                            },
                            onMessage: function (messageData) {
                              // Callback fn when message is received
                              $(callbackDisplay).html(
                                '<b>Frame ID:</b> ' +
                                  messageData.iframe.id +
                                  ' <b>Message:</b> ' +
                                  messageData.message
                              )
                              alert(messageData.message)
                              document
                                .getElementsByTagName('iframe')[0]
                                .iFrameResizer.sendMessage('Hello back from parent page')
                            },
                            onClosed: function (id) {
                              // Callback fn when iFrame is closed
                              $(callbackDisplay).html('<b>IFrame (</b>' + id + '<b>) removed from page.</b>')
                            },
                    
                          })
                        </script>
                      </body>
                </html>
、、、

**Comment by tangye1234** [comment]
重点再把集中计算高度逻辑写出来，同时讲讲这个框架是如何传递 message 的
